service: auto-deploy-lambda

provider:
  name: aws
  region: ap-northeast-1
  timeout: 120

#  environment:
#    SLACK_WEBHOOK: ${env:SLACK_WEBHOOK}

package:
  exclude:
    - Dockerfile
    - docker-compose.yml

functions:
  test:
    handler: src/index.post
    description: "git actions to lambda"
    timeout: 60
