 on:
   push:
     branches:
       - remove

 name: Remove Lambda

 jobs:
   remove:
     name: Remove Lambda
     runs-on: ubuntu-18.04
     steps:
       - uses: actions/checkout@master

       - name: Setup Node.js
         uses: actions/setup-node@v1
         with:
           node-version: '10.x'

       - name: Install Serverless Framework
         run: npm install serverless -g

       - name: Remove Lambda
         run: sls remove -v
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}